// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnvfltaomsxewwojqtvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZudmZsdGFvbXN4ZXd3b2pxdHZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NzA5NjAsImV4cCI6MjA1OTU0Njk2MH0.sGoy5tBQIw6wYTskRlJ3EhQ_GVOTEXekC2N77HW9_Wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);